# -*- coding: utf-8 -*-
__author__ = 'yicong.xiao'

import os
from typing import List

import redis

from app.models.job import JobItem
from app.services.storage.db_controller import DBController
from app.services.storage.engine import engine
from app.services.storage.utils import session_scope

import scrapy
from scrapy.exceptions import DropItem
from scrapy.utils.project import get_project_settings

#logger = logging.getLogger(__name__)
settings = get_project_settings()

parsed_url_redis_cache_key = "parsed_url"

class JobCrawlerPipeline(object):

    def open_spider(self, spider):
        """
        spider 初始化时创建数据库连接
        :param spider: 启动的 spider
        """
        
        self.redis_db = redis.Redis(
                                    host=os.getenv("REDIS_HOST"),
                                    port=10771,
                                    decode_responses=True,
                                    username="default",
                                    password=os.getenv("REDIS_PASSWORD"),
                                )
        
        self.db_controller = DBController(engine)
        self.parsed_job_items: List[JobItem] = []

    def close_spider(self, spider):
        
        # clear out SQL items pending insertion
        if self.parsed_job_items:
            with session_scope(self.db_controller.session_maker) as session:
                self.db_controller.insert_job_item(session, self.parsed_job_items)


    def process_item(self, item: scrapy.Item, spider):
        """
        This method is called on each `scrapy.Item` generated by spider.parse().

        Accumulate each received `item` to `self.parsed_job_items`, 
        bulk insert every 100 `item`s into db
        """

        if self.redis_db.hexists(parsed_url_redis_cache_key, item['id']):
            raise DropItem(f"Duplicate item found: {item['url']}")
        
        # record crawled url at redis
        self.redis_db.hset(parsed_url_redis_cache_key, item['id'], 0)
        self.parsed_job_items.append(JobItem.from_scrapy_item(item))

        # bulk insert
        if len(self.parsed_job_items) == 100:
            with session_scope(self.db_controller.session_maker) as session:
                self.db_controller.insert_job_item(session, self.parsed_job_items)

            self.parsed_job_items = []

        return item


 
