# -*- coding: utf-8 -*-
__author__ = "yicong.xiao"

import os
from typing import Any, List, Dict
import logging
import json
import uuid

from dotenv import load_dotenv
import redis
import scrapy
from scrapy.exceptions import DropItem
from scrapy.utils.project import get_project_settings

from app.config import get_project_root
from app.models.job import JobItem
from app.services.storage.db_controller import DBController
from app.services.storage.engine import engine
from app.services.storage.utils import session_scope
from app.services.language_modeling.open_ai_service_provider import (
    OpenAIServiceProvider,
)
from app.services.storage.zilliz_controller import ZillizController

# load .env
load_dotenv(os.path.join(get_project_root(), ".env"))

# logger = logging.getLogger(__name__)
settings = get_project_settings()

logging.basicConfig(filename=os.path.join(get_project_root(), "logs", "job_crawler.log"),
                    filemode='a',
                    format='%(asctime)s,%(msecs)03d %(name)s %(levelname)s %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S',)

logger = logging.getLogger(__name__)

parsed_url_redis_cache_key = "parsed_url"


class JobCrawlerPipeline(object):

    def open_spider(self, spider):
        """
        This method is called upon the creation of a spider. Initialize the db connections and embedding service.
        """
        logging.getLogger("scrapy").setLevel(logging.ERROR)  # Or logging.ERROR, logging.FATAL

        self.redis_db = redis.Redis(
            host=os.getenv("REDIS_HOST"),
            port=10771,
            decode_responses=True,
            username="default",
            password=os.getenv("REDIS_PASSWORD"),
        )

        self.num_batch_jobs = 0
        self.num_items_parsed = 0

        self.db_controller = DBController(engine)
        self.embedding_service = OpenAIServiceProvider(
            api_url=os.getenv("LLM_EMBEDDING_API_URL"),
            api_key=os.getenv("LLM_EMBEDDING_API_KEY"),
        )
        self.vector_db_controller = ZillizController(
            uri=os.getenv("ZILLIZ_URI"), token=os.getenv("ZILLIZ_TOKEN")
        )
        self.parsed_job_items: List[JobItem] = []
        self.batch_job_files: List[str] = []

    def close_spider(self, spider):

        #self.redis_db.bgsave()

        # clear out SQL items pending insertion
        if self.parsed_job_items:
            with session_scope(self.db_controller.session_maker) as session:
                self.db_controller.insert_job_item(session, self.parsed_job_items)
        
        # bulk insert into vector db
        if self.batch_job_files:
            for idx, batch_job_file in enumerate(self.batch_job_files):
                embeddings: List[Dict[str, Any]] = self.embedding_service.get_embedding_batch(
                    input_file_path=batch_job_file,
                    output_file_path=os.path.join(
                        get_project_root(), "files", f"batch_job_{idx}_output.jsonl"
                    ),
                )
                self.vector_db_controller.insert_job_items(embeddings)

                # update embedding status in SQL db
                with session_scope(self.db_controller.session_maker) as session:
                    self.db_controller.update_job_item_embedding_status_bulk(
                        session, [uuid.UUID(e["id"]) for e in embeddings], True
                    )

    def process_item(self, item: scrapy.Item, spider):
        """
        This method is called on each `scrapy.Item` generated by spider.parse()
        """

        if self.redis_db.hexists(parsed_url_redis_cache_key, str(item["id"])):
            return item

        
        self.parsed_job_items.append(JobItem.from_scrapy_item(item))
        self.num_items_parsed += 1

        if self.num_items_parsed % 100 == 0:
            logger.info(f"Processed {self.num_items_parsed} job items so far.")

        try:
            # bulk insert for every 10k job items
            if len(self.parsed_job_items) == 10000:
                logger.info(f"Starts to process batch {self.num_batch_jobs} with {len(self.parsed_job_items)} job items")
                # generate a batch job file for embedding
                batch_job_file = os.path.join(get_project_root(),"files", f"batch_job_{self.num_batch_jobs}.jsonl")
                self.batch_job_files.append(batch_job_file)
                self.num_batch_jobs += 1
                batch_data = [{'custom_id': str(j.id),
                                'method': 'POST',
                                'url': '/v1/embeddings',
                                'body': {'model': 'text-embedding-v4',
                                'input': str(j),
                                'encoding_format': 'float'}} for j in self.parsed_job_items]
                logger.info(f'Writing {len(batch_data)} job items to {batch_job_file}')
                with open(batch_job_file, "w", encoding="utf-8") as f:
                    for data in batch_data:
                        json.dump(data, f, ensure_ascii=False)
                        f.write("\n")
                logger.info(f'Writing completed')
                
                # bulk insert into sql db
                logger.info(f'Starting to bulk insert {len(self.parsed_job_items)} job items into SQL db')
                with session_scope(self.db_controller.session_maker) as session:
                    self.db_controller.insert_job_item(session, self.parsed_job_items)
                logger.info(f'Insertion completed')

                self.parsed_job_items = []
            
            # record crawled url at redis
            self.redis_db.hset(parsed_url_redis_cache_key, str(item["id"]), 0)
        except Exception as e:
            logger.error(f'Exception occured when parsing job item {item['id']} from url {item['url']}', exc_info=True)
        finally:
            return item
