# -*- coding: utf-8 -*-
__author__ = "yicong.xiao"

import os
from typing import List

from dotenv import load_dotenv
import redis
import scrapy
from scrapy.exceptions import DropItem
from scrapy.utils.project import get_project_settings

from app.config import get_project_root
from app.models.job import JobItem
from app.services.storage.db_controller import DBController
from app.services.storage.engine import engine
from app.services.storage.utils import session_scope
from app.services.language_modeling.open_ai_service_provider import (
    OpenAIServiceProvider,
)
from app.services.storage.zilliz_controller import ZillizController

# load .env
load_dotenv(os.path.join(get_project_root(), ".env"))

# logger = logging.getLogger(__name__)
settings = get_project_settings()

parsed_url_redis_cache_key = "parsed_url"


class JobCrawlerPipeline(object):

    def open_spider(self, spider):
        """
        This method is called upon the creation of a spider. Initialize the db connections and embedding service.
        """

        self.redis_db = redis.Redis(
            host=os.getenv("REDIS_HOST"),
            port=10771,
            decode_responses=True,
            username="default",
            password=os.getenv("REDIS_PASSWORD"),
        )

        self.db_controller = DBController(engine)
        self.embedding_service = OpenAIServiceProvider(
            api_url=os.getenv("LLM_EMBEDDING_API_URL"),
            api_key=os.getenv("LLM_EMBEDDING_API_KEY"),
        )
        self.vector_db_controller = ZillizController(
            uri=os.getenv("ZILLIZ_URI"), token=os.getenv("ZILLIZ_TOKEN")
        )
        self.parsed_job_items: List[JobItem] = []

    def close_spider(self, spider):

        self.redis_db.bgsave()

        # clear out SQL items pending insertion
        if self.parsed_job_items:
            with session_scope(self.db_controller.session_maker) as session:
                self.db_controller.insert_job_item(session, self.parsed_job_items)

    def process_item(self, item: scrapy.Item, spider):
        """
        This method is called on each `scrapy.Item` generated by spider.parse().

        Accumulate each received `item` to `self.parsed_job_items`,
        bulk insert every 10 `item`s into db
        """

        if self.redis_db.hexists(parsed_url_redis_cache_key, str(item["id"])):
            raise DropItem(f"Duplicate item found: {item['url']}")

        # record crawled url at redis
        self.redis_db.hset(parsed_url_redis_cache_key, str(item["id"]), 0)
        self.parsed_job_items.append(JobItem.from_scrapy_item(item))

        # bulk insert
        if len(self.parsed_job_items) == 10:

            # insert into sql db
            with session_scope(self.db_controller.session_maker) as session:
                self.db_controller.insert_job_item(session, self.parsed_job_items)

            # insert into vector db
            embeddings = self.embedding_service.get_embedding(
                model_name=os.getenv("LLM_EMBEDDING_API_MODEL_NAME"),
                input_txt=[str(job_item) for job_item in self.parsed_job_items],
                dimensions=1024,
            )

            assert len(embeddings) == len(self.parsed_job_items)  # sanity check

            embedding_to_be_inserted = [
                {"id": str(self.parsed_job_items.id[i]), "embedding": embeddings[i]}
                for i in range(len(embeddings))
            ]
            self.vector_db_controller.insert_job_items(embedding_to_be_inserted)

            self.parsed_job_items = []

        return item
